FROM docker/dev-environments-java

#Install vim
RUN apt-get -y update
RUN apt-get -y install vim
#Install JDK
RUN apt-get -y install default-jdk
RUN apt-get -y install gradle

#Migrate files in local dir
COPY ./deploy /frc
COPY ./deploy/git-hooks/* /frc/git-hooks
RUN chmod +x /frc/git-hooks/*

RUN git config --global user.name "LER-Programming"
RUN git config --global user.email "github.lakeeffectrobotics@gmail.com"
RUN git config --global core.hooksPath /frc/git-hooks