FROM docker/dev-environments-java

#Install vim
RUN apt-get -y update
RUN apt-get -y install vim
#Install JDK
RUN apt-get -y install default-jdk
RUN apt-get -y install gradle

#Migrate files in local dir
COPY ./deploy /ler
COPY ./deploy/git-hooks/* /ler/git-hooks
RUN chmod +x /ler/git-hooks/*

# Setup git for team use
RUN sh /ler/git-setup.sh