FROM docker/dev-environments-java

#Install vim
RUN apt-get -y update
RUN apt-get -y install vim
#Install JDK
RUN apt-get -y install default-jdk
RUN apt-get -y install gradle

#Migrate files in local dir
COPY ./deploy /frc
COPY ./deploy/git-hooks/* /frc/git-hooks
RUN chmod +x /frc/git-hooks/*
RUN chomd +x /frc/git-setup.sh

# Setup git for team use
RUN /frc/git-setup.sh